server:
  port: 8080

raft:
  nodeId: NODE_1
  peers:
    - http://localhost:8081
    - http://localhost:8082
  electionTimeoutMsMin: 150
  electionTimeoutMsMax: 300
  heartbeatIntervalMs: 50
  rpcTimeoutMs: 300
  maxElectionRetryBackoffMs: 500